[package]
name = "ratls-proxy"
version = "0.0.1"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"
url = "2.5"
